interface Props {
  globalFeatures: Record<string, unknown>
  declaredSettings: Record<string, unknown>
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="bg-gray-900 rounded-lg p-4">
      <h3 className="text-sm font-semibold text-gray-400 uppercase tracking-wide mb-3">{title}</h3>
      {children}
    </div>
  )
}

function Row({ label, value }: { label: string; value: unknown }) {
  let display: string
  if (value == null) display = '–'
  else if (typeof value === 'object') display = JSON.stringify(value)
  else display = String(value)
  return (
    <div className="flex justify-between py-1 border-b border-gray-800 last:border-0 gap-4">
      <span className="text-gray-400 text-xs shrink-0">{label}</span>
      <span className="text-gray-200 text-xs font-mono text-right break-all">{display}</span>
    </div>
  )
}

type NozzleEntry = [number, number]
type BedEntry    = [number, number]

export default function EventsView({ globalFeatures: gf, declaredSettings: ds }: Props) {
  const nozzleSeq = (gf.nozzle_setpoints_sequence ?? []) as NozzleEntry[]
  const bedSeq    = (gf.bed_setpoints_sequence    ?? []) as BedEntry[]
  const la        = (gf.linear_advance_summary    ?? {}) as Record<string, unknown>
  const jerk      = (gf.jerk_limits_last          ?? {}) as Record<string, unknown>
  const frMax     = (gf.feedrate_max_last         ?? {}) as Record<string, unknown>
  const acMax     = (gf.accel_max_last            ?? {}) as Record<string, unknown>
  const hs        = (ds.header_settings           ?? {}) as Record<string, string>

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">

      <Section title="Declared Settings">
        <Row label="Generated by"    value={ds.generated_by} />
        <Row label="Timestamp"       value={ds.timestamp} />
        <Row label="Printer model"   value={ds.printer_model} />
        <Row label="Nozzle diameter" value={ds.nozzle_diameter != null ? `${ds.nozzle_diameter} mm` : null} />
        <Row label="Filament type"   value={ds.filament_type} />
      </Section>

      <Section title="Header Settings (key = value)">
        {Object.keys(hs).length === 0
          ? <p className="text-gray-500 text-xs">None found.</p>
          : Object.entries(hs).map(([k, v]) => <Row key={k} label={k} value={v} />)
        }
      </Section>

      <Section title="Nozzle Temperature Events">
        {nozzleSeq.length === 0
          ? <p className="text-gray-500 text-xs">None.</p>
          : nozzleSeq.map(([lid, t], i) => (
              <Row key={i} label={`Layer ${lid}`} value={`${t} °C`} />
            ))
        }
      </Section>

      <Section title="Bed Temperature Events">
        {bedSeq.length === 0
          ? <p className="text-gray-500 text-xs">None.</p>
          : bedSeq.map(([lid, t], i) => (
              <Row key={i} label={`Layer ${lid}`} value={`${t} °C`} />
            ))
        }
      </Section>

      <Section title="Linear Advance (M900 K)">
        <Row label="Count"          value={la.count} />
        <Row label="Unique values"  value={(la.unique_values as number[] ?? []).join(', ')} />
        <Row label="First"          value={la.first_value} />
        <Row label="Last"           value={la.last_value} />
        <Row label="Min"            value={la.min_value} />
        <Row label="Max"            value={la.max_value} />
      </Section>

      <Section title="Motion Constraints">
        <Row label="Accel changes (M204)" value={String(gf.accel_changes_count ?? '–')} />
        <Row label="Accel unique vals"    value={(gf.accel_unique_values as number[] ?? []).join(', ')} />
        <Row label="Accel last"           value={gf.accel_last_value} />
        <Row label="Jerk X"               value={jerk.X} />
        <Row label="Jerk Y"               value={jerk.Y} />
        <Row label="Jerk Z"               value={jerk.Z} />
        <Row label="Jerk E"               value={jerk.E} />
        {Object.entries(frMax).map(([ax, v]) => (
          <Row key={`fr_${ax}`} label={`Max feedrate ${ax}`} value={`${v} mm/s`} />
        ))}
        {Object.entries(acMax).map(([ax, v]) => (
          <Row key={`ac_${ax}`} label={`Max accel ${ax}`} value={`${v} mm/s²`} />
        ))}
      </Section>

      <Section title="Dynamics / Quality Proxies">
        <Row label="Feedrate CV (extrude)"  value={`${(Number(gf.feedrate_cv_extrude ?? 0) * 100).toFixed(1)} %`} />
        <Row label="Feedrate σ (extrude)"   value={`${gf.feedrate_std_extrude} mm/min`} />
        <Row label="Feedrate σ (travel)"    value={`${gf.feedrate_std_travel} mm/min`} />
        <Row label="Speed-jump rate"        value={`${(Number(gf.speed_jump_rate ?? 0) * 100).toFixed(1)} %`} />
        <Row label="G92 resets"             value={gf.num_g92_resets} />
        <Row label="M73 progress updates"   value={gf.m73_count} />
      </Section>

      <Section title="Retraction / Wipe">
        <Row label="Retraction count"       value={gf.retraction_count} />
        <Row label="Mean retract length"    value={`${gf.retraction_length_mean} mm`} />
        <Row label="Retract speed (mean)"   value={`${gf.retraction_speed_mean} mm/min`} />
        <Row label="Retracts / meter"       value={gf.retracts_per_meter} />
        <Row label="Retract–wipe correlation" value={`${(Number(gf.retract_wipe_correlation ?? 0) * 100).toFixed(1)} %`} />
        <Row label="Wipe blocks total"      value={gf.num_wipe_blocks} />
        <Row label="Wipe total path"        value={`${gf.wipe_total_path_mm} mm`} />
        <Row label="Wipe total time"        value={`${gf.wipe_total_time_est_s} s`} />
      </Section>

    </div>
  )
}
